# order-create-new
POST http://localhost:8082/api/order HTTP/1.1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "customerId":"1",
  "title":"new order",
  "amount":"100",
  "ticketNum":100
}

###

# ticket_lock_ticket  这个接口不能真正实现锁票， 因为会在多线程的情况下， 后者覆盖前者的结果
POST http://localhost:8083/api/ticket/lock HTTP/1.1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


{
  "customerId":"1",
  "ticketNum":"100"
}
###

# 分别操作下面两条接口， 先执行完成的会update进DB， 后执行的不会覆盖

# ticket_lock_ticket   这个接口能真正实现锁票， 通过SQL的幂等性方法实现
POST http://localhost:8083/api/ticket/lock2 HTTP/1.1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


{
  "customerId":"1",
  "ticketNum":"100"
}
###

###

# ticket_lock_ticket   这个接口能真正实现锁票， 通过SQL的幂等性方法实现
POST http://localhost:8083/api/ticket/lock2 HTTP/1.1
Accept: */*
Cache-Control: no-cache
Content-Type: application/json


{
  "customerId":"2",
  "ticketNum":"100"
}
###



###


# referrence format: https://marketplace.visualstudio.com/items?itemName=humao.rest-client