server:
  port: 8761
spring:
  application:
    name: registry
#  security:
#    basic:
#      enabled: true
#    user:
#      name: evan
#      password: 123
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/